baseURL: "https://shantanu-sg-01.github.io" 
title: Shantanu S. Gulawani
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: About me
          url: books/
          weight: 4 
        - name: Research 
          url: papers/
          weight: 3
        - name: For Students
          url: courses/
          weight: 2
        - name: Blog
          url: https://shantanusg.substack.com
          weight: 5

params:
    description: "I am Assistant Professor of Aerospace Engineering at MVJ College of Engineering. I am interested in Design, Optimization, Computing and Coding."
    author: Shantanu S. Gulawani
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["For Students","Research","About me","Blog"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: true
    math: true
    profileMode:
          enabled: true
          title: Shantanu S. Gulawani
          subtitle: >
          Welcome!
          
          I am a faculty member in the Aerospace Engineering Department at MVJ College of Engineering, Bengaluru. This website serves as a hub for my academic activities — a place where I share my research directions, student collaboration opportunities, and thoughts on engineering education and scientific computing.
          
          My research lies at the intersection of computational methods, numerical modeling, and modern software design for scientific applications. I explore ways to build robust, expressive, and high-performance computational tools — often drawing from the principles of declarative and functional programming, especially in the context of aerospace system simulation and design.
          
          Feel free to email me if you are interested in research collaborations, student projects, or mentoring conversations. I also maintain a Substack blog where I write about my research learnings, classroom ideas, and general observations from my academic journey. You can find my professional updates and connect with me on LinkedIn as well.
          
          If you would like to book a time slot to discuss a project, idea, or collaboration, you can do so here https://calendly.com/shantanu_as-mvjce/office-houre-in-person.
          
          Explore the site - 
          
          * The Research page - highlights areas I work on and ongoing directions.
          
          * The For Students page - contains all information about working with me and applying for research projects.
          
          * The Co-curricular section - showcases activities I’m involved in within the Aerospace department.
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: For Students
              url: papers/
            - name: Courses
              url: courses/
            - name: Co-curricular
              url: data/
            - name: Research
              url: books/
            - name: About me
              url: tags/
            - name: Blog
              url: https://shantanusg.substack.com

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:shantanu_as@mvjce.edu.in
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=hsilxtIAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/Shantanu-sg-01
        - name: LinkedIn
          url: https://www.linkedin.com/in/shantanu-gulawani-a133b2131

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Shantanu S. Gulawani"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
